# ref: http://docs.travis-ci.com/user/build-configuration

language: erlang

env:
    global:
        - DEPS_BUILD_DIR=$TRAVIS_BUILD_DIR/deps
        - DEPS_PREFIX=/usr/local
        - LZ4_URL="https://github.com/Cyan4973/lz4/archive/r123.tar.gz"
        - LJ_REPO="http://luajit.org/git/luajit-2.0.git"
    matrix:
        - LJ=LuaJIT-2.0 LJ_BR=master LJ_BIN=luajit-2.0.3
        - LJ=LuaJIT-2.1 LJ_BR=v2.1   LJ_BIN=luajit-2.1.0-alpha

before_install:
    - mkdir -p $DEPS_BUILD_DIR
    - sudo apt-get update -q

install:
    # install Lua busted
    - sudo apt-get install luarocks
    - sudo luarocks install busted
    # install LZ4
    - cd $DEPS_BUILD_DIR
    - wget $LZ4_URL -O lz4-r123.tar.gz
    - tar xzf lz4-r123.tar.gz && cd lz4-r123
    - sudo make PREFIX=$DEPS_PREFIX install
    # install LuaJIT
    - cd $DEPS_BUILD_DIR
    - git clone -b $LJ_BR $LJ_REPO luajit2.git && cd luajit2.git
    - sudo make PREFIX=$DEPS_PREFIX XCFLAGS+="-DLUAJIT_ENABLE_LUA52COMPAT" install

before_script:
    # back to home directory
    - cd $TRAVIS_BUILD_DIR
    # update shared libraries, check executables
    - sudo ldconfig && ls -lh /usr/local/lib
    - which $LJ_BIN

script:
    - sudo busted -v

notifications:
    email:
        on_success: change
        on_failure: always
