language: erlang

env:
    global:
        - DEPS_BUILD_DIR=$TRAVIS_BUILD_DIR/deps
        - DEPS_PREFIX=/usr/local
        - LZ4_URL="https://github.com/Cyan4973/lz4/archive/r123.tar.gz"
        - LJ20_URL="http://luajit.org/download/LuaJIT-2.0.3.tar.gz"
        - LJ21_REPO="http://luajit.org/git/luajit-2.0.git"
    matrix:
        - LUAJIT=LuaJIT-2.0  LUA_BIN=luajit-2.0.3
        - LUAJIT=LuaJIT-2.1  LUA_BIN=luajit-2.1.0-alpha

install:
    - sudo apt-get update -q
    - sudo apt-get install luarocks
    - sudo luarocks install busted
    - mkdir -p $DEPS_BUILD_DIR
    # install LZ4 r123
    - cd $DEPS_BUILD_DIR
    - wget $LZ4_URL -O lz4-r123.tar.gz
    - tar xzf lz4-r123.tar.gz && cd lz4-r123
    - sudo make PREFIX=$DEPS_PREFIX install
    # install LuaJIT 2.0 stable
    - cd $DEPS_BUILD_DIR
    - wget $LJ20_URL
    - tar xzf LuaJIT-2.0.3.tar.gz && cd LuaJIT-2.0.3
    - sudo make PREFIX=$DEPS_PREFIX XCFLAGS+="-DLUAJIT_ENABLE_LUA52COMPAT" install
    # install LuaJIT 2.1 alpha
    - cd $DEPS_BUILD_DIR
    - git clone -b v2.1 $LJ21_REPO luajit-2.1.git && cd luajit-2.1.git
    - sudo make PREFIX=$DEPS_PREFIX XCFLAGS+="-DLUAJIT_ENABLE_LUA52COMPAT" install
    # update shared libs
    - sudo ldconfig && ls -lh /usr/local/lib
    # done, back to home directory
    - cd $TRAVIS_BUILD_DIR

script:
    - which $LUA_BIN
    - sudo busted -v

notifications:
    email:
        on_success: change
        on_failure: always
