# ref: http://docs.travis-ci.com/user/build-configuration

language: erlang

env:
    global:
        - DEPS_BUILD_DIR=$TRAVIS_BUILD_DIR/deps
        - DEPS_PREFIX=/usr/local
        - LZ4_VER=r130
        - LUAROCKS_VER=2.2.1
        - LZ4_URL="https://github.com/Cyan4973/lz4/archive/$LZ4_VER.tar.gz"
        - LUAROCKS_URL="http://keplerproject.github.io/luarocks/releases/luarocks-$LUAROCKS_VER.tar.gz"
        - LJ_REPO="http://luajit.org/git/luajit-2.0.git"
    matrix:
        - LJ=luajit-2.0 LJ_BR=master LJ_BIN_SUFFIX=jit-2.0.4       LJ_BIN="lua$LJ_BIN_SUFFIX"
        - LJ=luajit-2.1 LJ_BR=v2.1   LJ_BIN_SUFFIX=jit-2.1.0-alpha LJ_BIN="lua$LJ_BIN_SUFFIX"

before_install:
    - mkdir -p $DEPS_BUILD_DIR
    - sudo apt-get update -q

install:
    # install LZ4
    - cd $DEPS_BUILD_DIR
    - wget $LZ4_URL -O lz4-$LZ4_VER.tar.gz
    - tar xzf lz4-$LZ4_VER.tar.gz && cd lz4-$LZ4_VER
    - sudo make PREFIX=$DEPS_PREFIX install
    # install LuaJIT
    - cd $DEPS_BUILD_DIR
    - git clone -b $LJ_BR $LJ_REPO luajit2.git && cd luajit2.git
    - sudo make PREFIX=$DEPS_PREFIX XCFLAGS+="-DLUAJIT_ENABLE_LUA52COMPAT" install
    # install luarocks
    - cd $DEPS_BUILD_DIR
    - wget $LUAROCKS_URL -O luarocks-$LUAROCKS_VER.tar.gz
    - tar xzf luarocks-$LUAROCKS_VER.tar.gz && cd luarocks-$LUAROCKS_VER
    - ./configure
      --lua-version=5.1 --lua-suffix=$LJ_BIN_SUFFIX --with-lua-include="/usr/local/include/$LJ"
    - sudo make build install
    # install busted
    - sudo luarocks install busted

before_script:
    # back to home directory
    - cd $TRAVIS_BUILD_DIR
    # update shared libraries
    - sudo ldconfig -v 2> /dev/null | grep lz4
    # check executables
    - which $LJ_BIN
    - head -1 `which luarocks`

script:
    - sudo busted -v

notifications:
    email:
        on_success: change
        on_failure: always
